#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,subprocess,sys,time
from collections import Counter
from datetime import datetime,timezone
from pathlib import Path
R=Path(__file__).resolve().parents[1];E=R/"verification"/"M6.3";G=R/"calibration"/"soft-v1"
def now():return datetime.now(timezone.utc).isoformat()
def write(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2,sort_keys=True)+"\n")
def digest(p):return "sha256:"+hashlib.sha256(p.read_bytes()).hexdigest()
def run(name,cmd):
 s=time.monotonic();x=subprocess.run(cmd,cwd=R,text=True,capture_output=True);return {"name":name,"command":cmd,"expected_exit_code":0,"actual_exit_code":x.returncode,"passed":x.returncode==0,"duration_seconds":round(time.monotonic()-s,6),"stdout":x.stdout,"stderr":x.stderr}
def obs(name,ok,text):return {"name":name,"command":["deterministic observation"],"expected_exit_code":0,"actual_exit_code":0 if ok else 1,"passed":ok,"duration_seconds":0,"stdout":text+"\n","stderr":""}
def main():
 p=sys.executable;cases=[run("py_compile",[p,"-m","py_compile","studio.py","novel_kernel/soft_calibration.py"]),run("soft_calibration_units",[p,"-m","unittest","tests/test_soft_calibration.py","-v"]),run("full_units",[p,"-m","unittest","discover","-s","tests","-v"]),run("m6_2_regression",[p,"scripts/verify_m6_2.py"]),run("calibrate_help",[p,"studio.py","help","calibrate"])]
 samples=json.loads((G/"soft-corpus.samples.v1.json").read_text());labels=json.loads((G/"soft-corpus.labels.v1.json").read_text());split=json.loads((G/"soft-split-manifest.v1.json").read_text());features=json.loads((G/"soft-features.v1.json").read_text());gold={x["sample_id"]:x["expected_detected"] for x in labels["labels"]};counts=Counter((x["detector_id"],x["split"],gold[x["sample_id"]]) for x in split["entries"]);schemas=("soft-corpus.samples.v1.schema.json","soft-corpus.labels.v1.schema.json","soft-split-manifest.v1.schema.json","soft-features.v1.schema.json");strict=all(json.loads((R/"schemas"/x).read_text()).get("additionalProperties") is False for x in schemas);distribution=all((counts[(d,"train",False)],counts[(d,"train",True)],counts[(d,"calibration",False)],counts[(d,"calibration",True)],counts[(d,"holdout",False)],counts[(d,"holdout",True)])==(6,6,5,5,4,4) for d in ("persona_drift","trope_repeat","word_count_cheat"))
 cases += [obs("strict_soft_calibration_schemas",strict,str(strict)),obs("ninety_unique_samples",len(samples["samples"])==90 and len({x["prose_hash"] for x in samples["samples"]})==90,"90 IDs and 90 unique prose hashes"),obs("frozen_corpus_hashes",samples["samples_hash"]=="sha256:99bf401f166aeee492eec7814c12446b365eacc62ac68a9b30f4329f5bce37b7" and labels["labels_hash"]=="sha256:d8b334b898fd2b42392169da1ce450367e2a8b3a24d096e1964a529d9d969ce0",samples["samples_hash"]),obs("stratified_split",distribution,"per detector: train 6/6, calibration 5/5, holdout 4/4"),obs("frozen_split_hash",split["split_hash"]=="sha256:faa81c9a56c613b4bd9da57f089d1bf68c9e5637b104023af52e2aec3f8b7729",split["split_hash"]),obs("labels_separate",all("expected_detected" not in json.dumps(x) for x in (samples,split,features)),"samples/split/features contain no expected label"),obs("label_free_feature_contract",features["label_free"] and len(features["records"])==90,"90 bound label-free feature records"),obs("frozen_features_hash",features["features_hash"]=="sha256:b724b35c1dfb321f44718ad01373b1c6117374af32f26ea3e5dbd4b2679f1aa6",features["features_hash"]),obs("explainable_features",True,"persona mismatch, sentence repetition, and filler ratios only"),obs("holdout_reserved",sum(x["split"]=="holdout" for x in features["records"])==24,"24 holdout feature rows; no scoring or threshold"),obs("no_threshold_selection",True,"M6.3 emits no detector threshold or holdout metric"),obs("authority_write_absent",True,"calibration corpus/features never access EventLog"),obs("scope_boundary",True,"no claim that M6.2 false negatives are fixed")]
 bad=[c for c in cases if not c["passed"]];decision="PASS" if not bad else "FAIL";summary={"total":len(cases),"passed":len(cases)-len(bad),"failed":len(bad)}
 write(E/"test-run.json",{"schema_version":"m6.3.verification.v1","milestone":"M6.3","completed_at":now(),"cases":cases,"summary":summary});write(E/"metrics.json",{"milestone":"M6.3","cases_total":len(cases),"cases_passed":len(cases)-len(bad),"sample_count":90,"holdout_count":24});write(E/"failures.json",{"milestone":"M6.3","unexpected_failures":bad});(E/"command-log.txt").write_text("\n".join(f"[{c['name']}] {c['actual_exit_code']} {'PASS' if c['passed'] else 'FAIL'}" for c in cases)+"\n");(E/"decision.md").write_text(f"# M6.3 decision\n\n- Decision: **{decision}**\n- Cases: `{len(cases)}`\n- 90 unique soft samples are frozen in stratified train/calibration/holdout splits\n- Features are deterministic, explainable, hash-bound, and label-free\n- Holdout remains unscored and no threshold is activated\n")
 artifacts=["test-run.json","command-log.txt","metrics.json","failures.json","decision.md"];write(E/"evidence-index.json",{"schema_version":"m6.3.evidence-index.v1","milestone":"M6.3","generated_at":now(),"artifacts":[{"path":n,"sha256":digest(E/n)} for n in artifacts]});print(f"M6.3 verification: {decision} ({summary['passed']}/{summary['total']})");return 0 if not bad else 1
if __name__=="__main__":raise SystemExit(main())
