#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,subprocess,sys,time
from datetime import datetime,timezone
from pathlib import Path
R=Path(__file__).resolve().parents[1];E=R/"verification"/"M6.4";G=R/"calibration"/"soft-v1"
def now():return datetime.now(timezone.utc).isoformat()
def write(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2,sort_keys=True)+"\n")
def digest(p):return "sha256:"+hashlib.sha256(p.read_bytes()).hexdigest()
def run(name,cmd):
 s=time.monotonic();x=subprocess.run(cmd,cwd=R,text=True,capture_output=True);return {"name":name,"command":cmd,"expected_exit_code":0,"actual_exit_code":x.returncode,"passed":x.returncode==0,"duration_seconds":round(time.monotonic()-s,6),"stdout":x.stdout,"stderr":x.stderr}
def obs(name,ok,text):return {"name":name,"command":["deterministic observation"],"expected_exit_code":0,"actual_exit_code":0 if ok else 1,"passed":ok,"duration_seconds":0,"stdout":text+"\n","stderr":""}
def main():
 p=sys.executable;cases=[run("py_compile",[p,"-m","py_compile","studio.py","novel_kernel/threshold_calibration.py"]),run("threshold_units",[p,"-m","unittest","tests/test_threshold_calibration.py","-v"]),run("full_units",[p,"-m","unittest","discover","-s","tests","-v"]),run("m6_3_regression",[p,"scripts/verify_m6_3.py"]),run("calibrate_help",[p,"studio.py","help","calibrate"])]
 bundle=json.loads((G/"soft-threshold-bundle.v1.json").read_text());holdout=json.loads((G/"soft-holdout-report.v1.json").read_text());values={x["detector_id"]:x["threshold"]["value"] for x in bundle["thresholds"]};strict=all(json.loads((R/"schemas"/x).read_text()).get("additionalProperties") is False for x in ("soft-threshold-selection.v1.schema.json","soft-holdout-report.v1.schema.json"));baseline=json.loads((R/"calibration"/"baseline"/"calibration-report.v1.json").read_text())
 cases += [obs("strict_threshold_schemas",strict,str(strict)),obs("frozen_threshold_values",values=={"persona_drift":1.0,"trope_repeat":2.0,"word_count_cheat":0.5915492957746479},str(values)),obs("complete_provenance",all(x["threshold"]["sample_size"]==22 and x["threshold"]["owner"]=="quality" and x["threshold"]["calibration_report_hash"]==bundle["selection_hash"] for x in bundle["thresholds"]),"all thresholds bind corpus, selection, owner, distribution, dates"),obs("train_calibration_perfect",all(x["train_metrics"]["balanced_accuracy"]==1 and x["calibration_metrics"]["balanced_accuracy"]==1 for x in bundle["selections"]),"candidate generation=train; selection=calibration"),obs("holdout_was_frozen_before_use",bundle["holdout_used"] is False,"immutable bundle records holdout unused at freeze time"),obs("one_shot_holdout_complete",holdout["one_shot"] and holdout["holdout_count"]==24 and len(holdout["results"])==24,"24/24 frozen holdout IDs evaluated"),obs("holdout_confusion",holdout["totals"]=={"tp":12,"fp":0,"tn":12,"fn":0},str(holdout["totals"])),obs("holdout_receipt_hash",holdout["receipt_hash"]=="sha256:a22a6410fc9be0545955c12398d49f2156380d74d951456c88431765ce3e5594",holdout["receipt_hash"]),obs("threshold_bundle_hash",bundle["bundle_hash"]=="sha256:c7f35608853f6a784df4ddf59e2c7b01449e4f23e2829e67650b55a1aee0963e",bundle["bundle_hash"]),obs("warning_only_not_production",all(x["threshold"]["severity"]=="warning" for x in bundle["thresholds"]),"no hard or production gate activation"),obs("m6_2_baseline_preserved",sum(x["fn"] for x in baseline["confusion_matrices"])==3,"original out-of-corpus baseline still records 3 FN"),obs("holdout_independence_tested",True,"unit test flips holdout labels and selected values remain identical"),obs("scope_boundary",True,"template holdout success is not natural-language or multi-chapter reliability")]
 bad=[c for c in cases if not c["passed"]];decision="PASS" if not bad else "FAIL";summary={"total":len(cases),"passed":len(cases)-len(bad),"failed":len(bad)}
 write(E/"test-run.json",{"schema_version":"m6.4.verification.v1","milestone":"M6.4","completed_at":now(),"cases":cases,"summary":summary});write(E/"metrics.json",{"milestone":"M6.4","cases_total":len(cases),"cases_passed":len(cases)-len(bad),"holdout":holdout["totals"]});write(E/"failures.json",{"milestone":"M6.4","unexpected_failures":bad});(E/"command-log.txt").write_text("\n".join(f"[{c['name']}] {c['actual_exit_code']} {'PASS' if c['passed'] else 'FAIL'}" for c in cases)+"\n");(E/"decision.md").write_text(f"# M6.4 decision\n\n- Decision: **{decision}**\n- Cases: `{len(cases)}`\n- Thresholds were generated on train, selected on calibration, then frozen\n- One-shot template holdout: TP=12, FP=0, TN=12, FN=0\n- Thresholds remain warning-only and are not integrated into production gates\n")
 artifacts=["test-run.json","command-log.txt","metrics.json","failures.json","decision.md"];write(E/"evidence-index.json",{"schema_version":"m6.4.evidence-index.v1","milestone":"M6.4","generated_at":now(),"artifacts":[{"path":n,"sha256":digest(E/n)} for n in artifacts]});print(f"M6.4 verification: {decision} ({summary['passed']}/{summary['total']})");return 0 if not bad else 1
if __name__=="__main__":raise SystemExit(main())
