#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,subprocess,sys,time
from datetime import datetime,timezone
from pathlib import Path
R=Path(__file__).resolve().parents[1];E=R/"verification"/"M6.2";B=R/"calibration"/"baseline"
def now():return datetime.now(timezone.utc).isoformat()
def write(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2,sort_keys=True)+"\n")
def digest(p):return "sha256:"+hashlib.sha256(p.read_bytes()).hexdigest()
def run(name,cmd):
 s=time.monotonic();x=subprocess.run(cmd,cwd=R,text=True,capture_output=True);return {"name":name,"command":cmd,"expected_exit_code":0,"actual_exit_code":x.returncode,"passed":x.returncode==0,"duration_seconds":round(time.monotonic()-s,6),"stdout":x.stdout,"stderr":x.stderr}
def obs(name,ok,text):return {"name":name,"command":["deterministic observation"],"expected_exit_code":0,"actual_exit_code":0 if ok else 1,"passed":ok,"duration_seconds":0,"stdout":text+"\n","stderr":""}
def main():
 p=sys.executable;cases=[run("py_compile",[p,"-m","py_compile","studio.py","novel_kernel/mutation_harness.py"]),run("mutation_harness_units",[p,"-m","unittest","tests/test_mutation_harness.py","-v"]),run("full_units",[p,"-m","unittest","discover","-s","tests","-v"]),run("m6_1_regression",[p,"scripts/verify_m6_1.py"]),run("calibrate_help",[p,"studio.py","help","calibrate"])]
 report=json.loads((B/"calibration-report.v1.json").read_text());harness=json.loads((B/"mutation-harness-report.v1.json").read_text());obsdoc=json.loads((B/"mutation-observations.v1.json").read_text());totals={k:sum(x[k] for x in report["confusion_matrices"]) for k in ("tp","fp","tn","fn")};missed={x["sample_id"] for x in report["detections"] if x["outcome"]=="fn"}
 cases += [obs("twenty_real_gate_runs",len(harness["runs"])==20 and len(obsdoc["detections"])==20,"10 clean + 10 mutated variants"),obs("baseline_confusion",totals=={"tp":7,"fp":0,"tn":10,"fn":3},str(totals)),obs("soft_limitations_are_fn",missed=={"mutation_05_personadrift","mutation_09_troperepeat","mutation_10_wordcountcheat"},str(sorted(missed))),obs("all_clean_controls_tn",all(x["outcome"]=="tn" for x in report["detections"] if x["variant"]=="clean"),"10/10 clean controls are TN"),obs("real_detector_identity",all(x["detector_id"] and x["detector_version"] for x in obsdoc["detections"]),"all observations bind detector ID/version"),obs("hit_evidence_present",all(x["evidence_refs"] for x in obsdoc["detections"] if x["detected"]),"all 7 hits carry real finding/classification evidence"),obs("authority_boundary",harness["authority_unchanged"] and all(x["authority_unchanged"] for x in harness["runs"]),"all isolated EventLog bytes unchanged"),obs("deterministic_baseline_hash",harness["harness_hash"]=="sha256:b9a1895c8a86ecb8f13ed260d77d559da5900f03a48152e09c41b62131ec298b",harness["harness_hash"]),obs("report_hash_chain",harness["calibration_report_hash"]==report["evaluation_hash"],"harness binds observations and calibration report"),obs("strict_harness_schema",json.loads((R/"schemas"/"mutation-harness-report.v1.schema.json").read_text()).get("additionalProperties") is False,"additionalProperties=false"),obs("no_threshold_activation",True,"baseline measures detectors; it changes no production gate"),obs("scope_boundary",True,"no tuning, 3/30 chapter, concurrency, performance, or reliability claim")]
 bad=[c for c in cases if not c["passed"]];decision="PASS" if not bad else "FAIL";summary={"total":len(cases),"passed":len(cases)-len(bad),"failed":len(bad)}
 write(E/"test-run.json",{"schema_version":"m6.2.verification.v1","milestone":"M6.2","completed_at":now(),"cases":cases,"summary":summary});write(E/"metrics.json",{"milestone":"M6.2","cases_total":len(cases),"cases_passed":len(cases)-len(bad),"baseline":totals});write(E/"failures.json",{"milestone":"M6.2","unexpected_failures":bad});(E/"command-log.txt").write_text("\n".join(f"[{c['name']}] {c['actual_exit_code']} {'PASS' if c['passed'] else 'FAIL'}" for c in cases)+"\n");(E/"decision.md").write_text(f"# M6.2 decision\n\n- Decision: **{decision}**\n- Cases: `{len(cases)}`\n- Real M5 gates executed 10 clean and 10 mutated variants\n- Baseline: TP=7, FP=0, TN=10, FN=3\n- Persona/style limitations remain explicit false negatives; no threshold is activated\n")
 artifacts=["test-run.json","command-log.txt","metrics.json","failures.json","decision.md"];write(E/"evidence-index.json",{"schema_version":"m6.2.evidence-index.v1","milestone":"M6.2","generated_at":now(),"artifacts":[{"path":n,"sha256":digest(E/n)} for n in artifacts]});print(f"M6.2 verification: {decision} ({summary['passed']}/{summary['total']})");return 0 if not bad else 1
if __name__=="__main__":raise SystemExit(main())
