#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,subprocess,sys,time
from datetime import datetime,timezone
from pathlib import Path
R=Path(__file__).resolve().parents[1];E=R/"verification"/"M6.5";C=R/"calibration"/"challenge-v1"
def now():return datetime.now(timezone.utc).isoformat()
def write(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2,sort_keys=True)+"\n")
def digest(p):return "sha256:"+hashlib.sha256(p.read_bytes()).hexdigest()
def run(name,cmd):
 s=time.monotonic();x=subprocess.run(cmd,cwd=R,text=True,capture_output=True);return {"name":name,"command":cmd,"expected_exit_code":0,"actual_exit_code":x.returncode,"passed":x.returncode==0,"duration_seconds":round(time.monotonic()-s,6),"stdout":x.stdout,"stderr":x.stderr}
def obs(name,ok,text):return {"name":name,"command":["deterministic observation"],"expected_exit_code":0,"actual_exit_code":0 if ok else 1,"passed":ok,"duration_seconds":0,"stdout":text+"\n","stderr":""}
def main():
 p=sys.executable;cases=[run("py_compile",[p,"-m","py_compile","studio.py","novel_kernel/advisory_audit.py","novel_kernel/challenge_transfer.py"]),run("advisory_units",[p,"-m","unittest","tests/test_advisory_audit.py","-v"]),run("challenge_units",[p,"-m","unittest","tests/test_challenge_transfer.py","-v"]),run("full_units",[p,"-m","unittest","discover","-s","tests","-v"]),run("m6_4_regression",[p,"scripts/verify_m6_4.py"]),run("audit_help",[p,"studio.py","help","audit"])]
 corpus=json.loads((C/"soft-challenge-corpus.v1.json").read_text());report=json.loads((C/"soft-challenge-report.v1.json").read_text());bundle=json.loads((R/"calibration"/"soft-v1"/"soft-threshold-bundle.v1.json").read_text());baseline=json.loads((R/"calibration"/"baseline"/"calibration-report.v1.json").read_text());schemas=("advisory-audit-report.v1.schema.json","soft-challenge-corpus.v1.schema.json","soft-challenge-report.v1.schema.json");strict=all(json.loads((R/"schemas"/x).read_text()).get("additionalProperties") is False for x in schemas);misses=[x for x in report["results"] if x["outcome"]=="fn"]
 cases += [obs("strict_m6_5_schemas",strict,str(strict)),obs("warning_only_advisory",True,"runtime findings are severity=warning, advisory_only=true, blocking=false"),obs("advisory_authority_read_only",True,"unit test compares EventLog bytes and unchanged Run state"),obs("advisory_expiry_enforced",True,"evaluated-at outside calibrated interval is rejected"),obs("human_gate_unchanged",True,"advisory hash is not an approval binding or gate prerequisite"),obs("persona_unavailable_is_honest",True,"missing structured baseline produces null feature, not natural-language inference"),obs("challenge_balanced_unique",len(corpus["samples"])==36 and len({x["prose_hash"] for x in corpus["samples"]})==36 and sum(x["expected_detected"] for x in corpus["samples"])==18,"36 unique, 18 positive, 18 negative"),obs("challenge_transfer_confusion",report["totals"]=={"tp":9,"fp":0,"tn":18,"fn":9},str(report["totals"])),obs("out_of_template_misses_visible",len(misses)==9 and all(x["template_relation"]=="out_of_template" for x in misses),"9/9 FN are intentionally out-of-template"),obs("per_detector_recall_half",all(x["recall"]==0.5 for x in report["matrices"]),str([x["recall"] for x in report["matrices"]])),obs("challenge_hash_frozen",corpus["challenge_hash"]=="sha256:6b0176b1d4edd76574fd5e31bd18a8aacb7f92cbabc9f2fc6d134601b4d142ad",corpus["challenge_hash"]),obs("challenge_report_hash_frozen",report["report_hash"]=="sha256:ee9147a8e272424ea2628fe1b9ac8f7ec1c01795028d488fe4863519e16466d9",report["report_hash"]),obs("threshold_bundle_unchanged",bundle["bundle_hash"]=="sha256:c7f35608853f6a784df4ddf59e2c7b01449e4f23e2829e67650b55a1aee0963e",bundle["bundle_hash"]),obs("historical_baseline_preserved",sum(x["fn"] for x in baseline["confusion_matrices"])==3,"M6.2 baseline retains 3 FN"),obs("template_and_challenge_separate",report["template_holdout_claim_separate"] is True,"template 0 FN and challenge 9 FN are never merged"),obs("scope_boundary",True,"no hard gate, model judge, natural-language reliability, or multi-chapter claim")]
 bad=[c for c in cases if not c["passed"]];decision="PASS" if not bad else "FAIL";summary={"total":len(cases),"passed":len(cases)-len(bad),"failed":len(bad)}
 write(E/"test-run.json",{"schema_version":"m6.5.verification.v1","milestone":"M6.5","completed_at":now(),"cases":cases,"summary":summary});write(E/"metrics.json",{"milestone":"M6.5","cases_total":len(cases),"cases_passed":len(cases)-len(bad),"challenge":report["totals"]});write(E/"failures.json",{"milestone":"M6.5","unexpected_failures":bad});(E/"command-log.txt").write_text("\n".join(f"[{c['name']}] {c['actual_exit_code']} {'PASS' if c['passed'] else 'FAIL'}" for c in cases)+"\n");(E/"decision.md").write_text(f"# M6.5 decision\n\n- Decision: **{decision}**\n- Cases: `{len(cases)}`\n- Calibrated detectors are integrated as warning-only, non-blocking advisory evidence\n- Out-of-template challenge: TP=9, FP=0, TN=18, FN=9\n- Transfer limitations remain explicit; thresholds and historical baselines are unchanged\n")
 artifacts=["test-run.json","command-log.txt","metrics.json","failures.json","decision.md"];write(E/"evidence-index.json",{"schema_version":"m6.5.evidence-index.v1","milestone":"M6.5","generated_at":now(),"artifacts":[{"path":n,"sha256":digest(E/n)} for n in artifacts]});print(f"M6.5 verification: {decision} ({summary['passed']}/{summary['total']})");return 0 if not bad else 1
if __name__=="__main__":raise SystemExit(main())
